version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
  backend:
    build: ./backend
    ports:
      - "5001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: myapp
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
